### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by floooh** [floooh/fibs#1]
- [x] emsdk install / wasisdk install should check if sdk directory already exists and ask to delete instead of throwing a git error
- [x] need a target property `link_directories`
- [x] running cmake with --parallel may kill build performance on ARM Macs (too many clang processes, using up all memory)
- [x] add a `# machine generated, don't edit` to the top of the generated CMakeLists.txt
- [x] IConfigPhaseInfo directory info funcs cannot have the config name as optional!
- [x] ~~`./fibs diag configs` for the builtin configs should check the host platform~~ (wasn't also the case in fips)
- [x] schema validation should allow optional properties to exist as `undefined`
- [x] cmake code-gen bug: `b.addIncludeDirectories({ dirs: ['.'], language: 'cxx', buildMode: 'release' });` yields `include_directories(""$<$<CONFIG:RELEASE>:"$<$<COMPILE_LANGUAGE:CXX>:/Users/floh/projects/fibs-sokol-test/.>">"")`
- [x] publish 1.0 and add `^1` import version specififer to all fibs packages
- [x] cmake warning on Windows/VStudio: Manually specified variables were not used by build: CMAKE_BUILD_TYPE (e.g. put the 'isMultiConfigGenerator` back)
- [x] add an 'init' cmd (needs to be run via `deno run --allow-all jsr:@floooh/fibs init` in an existing directory)
- [x] port:
     - [x] sokol-doom: https://github.com/floooh/doom-sokol/pull/4
         - [x] webpage build!
         - [x] build instructions in readme
     - [x] v6502r https://github.com/floooh/v6502r/pull/37
     - [x] chips-test: https://github.com/floooh/chips-test/pull/42
     - [x] move sokol-tools to fibs https://github.com/floooh/sokol-tools/pull/208
- [x] replace all log.panic with throwing and put the error logging into a single top level catch
- [x] ~~`./fibs reset` should also run `deno clean` if possible~~ (doesn't work on windows)
- [x] ~~jobs: if addToTargetSources is true, also add a header search path~~ no, since that header search path would need to be magically derived from the output filenames
- [x] add IDE group property to targets
- [x] add and test `win-vscode-*` configs
    - [x] rename config-arch... etc to better match cmake generator properties?
- [x] vscode: check Emscripten debugging
- [x] default scope on interface targets should be 'interface'
- [x] low-prio: imported modules should be directly available via `p.importModule(importName, filename)` to allow projects to use/call custom exports on those modules (like the 'emrun()' helper function in `fibs-platforms/emscripten.ts`
- [x] properly deal with import options and unify with job args:
    - [x] import modules may define a single options type
    - [x] the importOptions() method becomes generic and gets a schema arg
    - [x] the schema also contains the default value and help text
- [x] ~~low-prio: imported targets should be grouped under an 'imports' IDE group~~ moved to 2.x wishlist
- [x] ~~low-prio: targets libs and frameworks should allow scope (public/private/interface)~~ moved to 2.x wishlist
- [x] ~~low-prio: projects should be able to define a default run target~~ moved to 2.x wishlist
- [x] ~~low-prio: maybe add varargs overloads for functions that take arrays?
- [x] ~~a project should be able to override the default config (via function)~~ => moved to 2.x wishlist
- [x] ~~Android support~~ => moved to 2.x wishlist
- [x] ~~iOS support~~ => moved to 2.x wishlist
- [x] proper pthread handling on Linux via Thread cmake package
- [x] Ubuntu/Debian compatibility (can't use cmake 4 as minimal version)
- [x] b.targetDistDir() and b.targetBuildDir() don't work from within target builder for the current target (add target builder helpers instead!!!)
- [x] MSVC:
    - [x] set debug session working directory
    - [x] copy target dlls into exe directory
- [x] fix emscripten runner on windows (emrun not found)
- [x] macOS/iOS: generate plist file (not directly, but can be configured via cmake target properties)
- [x] new git handling: fix 'you are leaving commit behind' warning during 'fibs update'
- [x] ~~import git dirs must be named like their import, not like the repository (because things like imgui docking vs main branch)~~ (fixed by appending @ref to the directory name)
- [x] implement a 'fibs reset' command which wipes the .fibs subdirectory
- [x] `fibs update` should completely skip linked imports (**especially** not delete them on --clean)
- [x] add a separate 'deps' field to targets, which may only reference targets, and use libs only for existing static link libs
- [x] StringArrays should be allowed to have null and undefined items (which are then ignored)
- [x] there should explicit wrapper types for the various records (e.g. `type TargetDescs = Record<string, TargetDesc>`
- [x] fibs update needs to happen in import order
- [x] compileDefinitions should be a Record<string,string>
- [x] Context should include host platform and host cpu arch
- [x] need a way to conditionally import .ts files by configs (e.g. glfw3 in sokol-samples if no `glfw-*` build config is used
- [x] fibs list targets should only show enabled targets (and get a new `--disabled` option)
- [x] hook 'fibs runjobs' into cmake file
- [x] target sources list must be build-time configurable
- [x] targets can be disabled based on build config
- [x] build configs: rename ```variables``` to ```cmakeVariables```
- [x] build configs should have an ```options: Record<string, any>``` field
- [x] ~~fibs clean should have sub-commands: config, import, target, sdk~~
- [x] 'fibs diag targets' needs to validate targets:
    - [x] only interface targets may have no sources
    - [x] interface target must not define public or private items (only generic array or interface)
- [x] 'fibs diag imports':
    - [x] check that import exists
    - [x] check if import has local modifications
    - [x] check if import has unpushed modifications
    - [x] ~~check if import has remote modifications~~
- [x] 'fibs update [import]'
- [x] 'fibs link [import] [local-dir]
- [x] 'fibs unlink [import]
- [x] imports
    - [x] imports with embedded ```fibs.ts``` file
    - [x] imports with locally defined ```ProjectDesc```
- [x] WASI support (via WASI SDK)
- [x] inherited configs must merge arrays and records (not replace)
- [x] must be able to patch/extend existing config desc without having to inherit
- [x] global target defaults per platform (must be able to filter by language ~~=> for now just expect cmake generator expressions in the items, but this is ugly)~~
    - [x] cmake variables
    - [x] compile options
    - [x] include directories
    - [x] compile definitions
    - [x] link options
- [x] target defaults per config (must be able to filter by language)
    - [x] compile options
    - [x] include directories
    - [x] compile definitions
    - [x] link options
- [x] need a universal path alias system which allows to patch path strings into valid absolute paths, this is for instance needed in places where a string property cannot be identified as a path (for instance cmake variables which need to point to a file). The path aliases need to be patched at the last moment, because they may depend on the current build config
    - ```@root/``` always points to the current root project directory
    - ```@self/``` points to the root or import directory
    - ```@sdks/``` points to ```@root/.fibs/sdks/```
    - ```@build/``` points to the current config's build directory
    - ```@dist/``` points to the current config's dist directory
- [x] any actual relative path should be treated like starting with ```@self/```

**Comment by floooh** [comment]
Closed as completed, all new features will go into: https://github.com/floooh/fibs/issues/10
